@startuml リアルタイム表示画面の動作

actor "ユーザー"
box "mk-flask-web-app"
    participant "app.py(web)"
end box

box "mk-function-app"
    participant "app.py(core)"
end box

"ユーザー" -> "app.py(web)" : アクセス
return 管理画面表示

loop 5秒に1回
    "app.py(web)" -> "app.py(core)" : apiを呼び出す
    "app.py(core)" --> "app.py(web)": 空調の値(ダミー)を返す
    "app.py(web)" --> "ユーザー": 画面上の値に反映
end

@enduml